[package]
name = "resctl-bench"
version = "1.0.0"
authors = ["Tejun Heo <tj@kernel.org>"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/facebookexperimental/resctl-demo"
description = "Whole system resource control benchmarks with realistic scenarios"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rd-util = { path = "../rd-util" }
rd-hashd-intf = { path = "../rd-hashd-intf" }
rd-agent-intf = { path = "../rd-agent-intf" }
resctl-bench-intf = { path = "../resctl-bench-intf" }

anyhow = "^1.0"
chrono = "^0.4"
console = "^0.14"
env_logger = "^0.8"
indicatif = "^0.15"
lazy_static = "^1.4"
libc = "^0.2"
libflate = "^1.0"
linreg = "^0.2"
log = "^0.4"
num-traits = "^0.2"
plotlib = "^0.5"
quantiles = "^0.7"
rand = "^0.8"
scan_fmt = "^0.2"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
statistical = "^1.0"
statrs = "^0.13"
tar = "^0.4"
tempfile = "^3.2"
term_size = "^0.3"
thiserror = "^1.0"
