[package]
name = "resctl-bench"
version = "0.1.0"
authors = ["Tejun Heo <tj@kernel.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rd-hashd-intf = { path = "../rd-hashd-intf" }
rd-agent-intf = { path = "../rd-agent-intf" }
resctl-bench-intf = { path = "../resctl-bench-intf" }

anyhow = "^1.0"
chrono = "^0.4"
console = "^0.13"
indicatif = "^0.15"
lazy_static = "^1.4"
log = "^0.4"
num-traits = "^0.2"
quantiles = "^0.7"
scan_fmt = "^0.2"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
statistical = "^1.0"
term_size = "^0.3"
util = { path = "../util" }
