# Copyright (c) Facebook, Inc. and its affiliates
[package]
name = "rd-agent"
version = "0.1.0"
authors = ["Tejun Heo <tj@kernel.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rd-agent-intf = { path = "../rd-agent-intf" }
rd-hashd-intf = { path = "../rd-hashd-intf" }

anyhow = "1.0.26"
chrono = { version = "0.4.10", features = ["serde"] }
crossbeam = "0.7.3"
dbus = "0.8.1"
enum-iterator = "0.5.0"
glob = "0.3.0"
json = "0.12.1"
lazy_static = "1.4.0"
libc = "0.2.66"
linux_proc = "0.1.1"
log = "0.4.8"
procfs = "0.7.7"
proc-mounts = "0.2.3"
regex = "1.3.4"
scan_fmt = "0.2.4"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.47"
sysinfo = "0.10.4"
users = "0.9.1"
util = { path = "../util" }
